# Site settings
title: hedge-ops
email: mhedgpeth-hedge-ops-email@gmail.com
description: 'Operational excellence through operation and culture'
baseurl: "" # the subpath of your site, e.g. /blog
url: 'http://mhedgpeth.github.io'
enable_retina: false
permalink: :title
nav_list:
  Home : ['Home', '/', 'fa-home']
  About : ['About', '/author/michael', 'fa-user']
  Speaking : ['Speaking', '/speaking', 'fa-microphone']
  Contact : ['Contact', '/contact', 'fa-plane']
single_footer: '<p>The writer community loves your content. Writer &copy; 2016 <a href="/">latest posts</a></p>'
footer_links:
    About: ['About', '/about']


# Build settings
# markdown: kramdown


# Image Sizes

# sidebar image 1432 X 2155
# thumbnail 368 X 620
# related 800 X 800
# post 1800 X 1200